// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class Questions
    {
        public Questions()
        {
            HistoryQuestion = new HashSet<HistoryQuestion>();
        }

        public int QuestionsId { get; set; }
        public string Question { get; set; }
        public int QuestionMark { get; set; }
        public int QuestionDifficulty { get; set; }
        public int SubjectsId { get; set; }
        public string? QuestionImageFileName { get; set; }
        public string Answer { get; set; }
        public string? AnswerImageFileName { get; set; }

        public virtual Subjects Subjects { get; set; }
        public virtual ICollection<HistoryQuestion> HistoryQuestion { get; set; }
    }
}