// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class HistoryQuestion
    {
        public int HistoryQuestionId { get; set; }
        public int HistoryId { get; set; }
        public int QuestionsId { get; set; }
        public int QuestionNumber { get; set; }

        public virtual History History { get; set; }
        public virtual Questions Questions { get; set; }
    }
}