// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class History
    {
        public History()
        {
            HistoryQuestion = new HashSet<HistoryQuestion>();
        }

        public int HistoryId { get; set; }
        public DateTime GeneratedTime { get; set; }
        public int UsersId { get; set; }

        public virtual Users Users { get; set; }
        public virtual ICollection<HistoryQuestion> HistoryQuestion { get; set; }
    }
}