// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class Subjects
    {
        public Subjects()
        {
            Questions = new HashSet<Questions>();
        }

        public int SubjectsId { get; set; }
        public string SubjectName { get; set; }

        public virtual ICollection<Questions> Questions { get; set; }
    }
}